version: '3'
services:
    server:
        build: .
        container_name: pentaho-server-ce
        environment:
            TZ: Europe/Warsaw
            DI_HOME: /home/pentaho/pentaho-server/pentaho-solutions/system/kettle
            CATALINA_OPTS: "-Xms4096m -Xmx6144m -XX:MaxPermSize=256m -Dsun.rmi.dgc.client.gcInterval=3600000 -Dsun.rmi.dgc.server.gcInterval=3600000 -Dpentaho.installed.licenses.file=$PENTAHO_INSTALLED_LICENSE_PATH -DDI_HOME=$DI_HOME"
        ports:
          - '8080:8080'
        restart: always
        networks:
            - pentaho-network
networks:
    pentaho-network: